include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = TestJITLess

TestJITLess_FILES = TestJITLess.m
TestJITLess_CFLAGS = -fobjc-arc
TestJITLess_INSTALL_PATH = /Applications/LiveContainer.app/Frameworks

include $(THEOS_MAKE_PATH)/library.mk
